import { observer } from "mobx-react-lite";
import { logout } from "../firestoreModel"
import { useNavigate, useLocation } from "react-router-dom";

export const HeaderView = observer(function HeaderRender(props) {

    const navigate = useNavigate();
    const location = useLocation();
    const isCartPage = location.pathname === "/cart";
    return (
        <div 
            className="
            flex flex-wrap justify-between gap-3 sm:gap-5 w-full p-3
            bg-gradient-to-br from-theme-50 via-theme-100 to-theme-200
            border-b border-theme-300
        "
        >
            <div 
                className="items-center order-1 text-theme-600
                    inline-block transform transition-transform 
                    duration-200 hover:scale-102 active:scale-98"
                onClick={() => navigate("/")}
            >
                <svg width="120" height="66" viewBox="0 0 146 66" xmlns="http://www.w3.org/2000/svg">

                    <text x="10" y="30" fontFamily="Arial, sans-serif" fontSize="27" fill="currentColor" className="text-theme-600" fontWeight="bold">
                        <tspan x="10" dy="0">Kampanj</tspan>
                        <tspan x="50" dy="26">Gruvan</tspan>
                    </text>
                </svg>
            </div>

            <div className="flex-grow order-last md:order-2 mx-auto my-auto min-w-[90%] md:min-w-[10%]">
                <div className="relative">

                    <input
                        type="text"
                        placeholder="Sök efter dina favoritbutiker"
                        value={props.searchInput}
                        onFocus={() => props.setSearchFocus(true)}
                        onChange={(e) => props.setCurrentSearch(e.target.value)}
                        className="
                            w-full pl-8 pr-4 py-3
                            border border-slate-300
                            rounded-full shadow-sm
                            bg-white/80 backdrop-blur
                            focus:outline-none
                            focus:ring-2 focus:ring-theme-200
                            focus:border-theme-400
                            transition
                            "
                    />
                </div>
            </div>

            <button
                onClick={() => {
                    props.handleGetLocation();
                    window.location.reload();
                }}
                className="
                    flex flex-col order-3 items-center px-2 py-1 rounded
                    hover:bg-theme-200/70
                    transition relative
                "                
                title={"Hitta min plats"}
            >
                {/* Map pin icon generated by ChatGPT */}
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-9 h-9 text-theme-700"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                >
                    <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5S10.62 6.5 12 6.5s2.5 1.12 2.5 2.5S13.38 11.5 12 11.5z" />
                </svg>

                <span className="text-xs text-slate-700 mt-1 whitespace-nowrap">
                    {props.city || "Stockholm"}
                </span>
            </button>

            <button 
                onClick={props.user ? logout : ()=> navigate("/login")}
                className="
                    ml-auto order-4 px-3 py-2 my-auto
                    bg-theme-600 text-white
                    font-semibold rounded-md shadow-sm text-sm
                    hover:bg-theme-500
                    focus:outline-none focus:ring-2 focus:ring-theme-300
                    active:bg-theme-700
                    transition-colors duration-150
                "
            >
                {props.user ? "Logga ut" : "Logga in"}
            </button>   


            <div 
                className="
                    relative inline-block my-auto mr-3 order-5
                    text-slate-700 hover:text-slate-900
                    active:scale-96 transition
                "
                onClick={() => {
                    if (isCartPage) {
                        navigate("/");
                    } else {
                        props.setSearchFocus(false);
                        navigate("/cart");
                    }
                }}
            >
                {isCartPage ? (
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-9">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                    </svg>
                ) : (
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-9">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                    </svg>
                )}
                {!isCartPage && (
                    <span className="
                    absolute -top-1 -right-1
                    bg-theme-700 text-white
                    text-xs w-4 h-4 flex items-center justify-center rounded-full
                    ">                        
                        {props.numberOfItemsInCart}
                    </span>
                )}
            </div>

        </div>
    );

})