import { observer } from "mobx-react-lite";
import { logout } from "../firestoreModel"
import { useNavigate } from "react-router-dom";

export const HeaderView = observer(function HeaderRender(props) {

    const navigate = useNavigate();

    return (
        <div 
            onFocus={props.setSearchFocus}
            className="flex flex-wrap justify-between gap-5 w-full p-3 bg-green-100"
        >

            <div 
                className="items-center order-1
                    inline-block transform transition-transform 
                    duration-200 hover:scale-102 active:scale-98"
                onClick={() => navigate("/")}
            >
                {/* Icon base generated by chatgpt */}
                <svg width="200" height="66" viewBox="0 0 200 66" xmlns="http://www.w3.org/2000/svg">
                    <circle cx="30" cy="30" r="20" fill="#34D399" />

                    <line x1="20" y1="25" x2="40" y2="25" stroke="white" strokeWidth="3" strokeLinecap="round"/>
                    <line x1="25" y1="20" x2="25" y2="40" stroke="white" strokeWidth="3" strokeLinecap="round"/>

                    <text x="70" y="30" fontFamily="Arial, sans-serif" fontSize="24" fill="#10B981" fontWeight="bold">
                        <tspan x="70" dy="0">Kampanj</tspan>
                        <tspan x="110" dy="26">Gruvan</tspan>
                    </text>
                </svg>
            </div>

            <div className="flex-grow order-last md:order-2 mx-auto my-auto min-w-[90%] md:min-w-[10%]">
                <div className="relative">
                    <span className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
                    🔍
                    </span>

                    <input
                        type="text"
                        placeholder="Sök efter dina favoritbutiker"
                        value={props.searchInput}
                        onChange={(e) => props.setCurrentSearch(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 border border-gray-300 
                            rounded-full shadow-sm focus:outline-none focus:ring-2 
                            focus:ring-green-200 focus:border-green-400 transition"
                    />
                </div>
            </div>

            <button 
                onClick={props.user ? logout : ()=> navigate("/login")}
                className="ml-auto order-3 px-3 py-2 my-auto bg-green-400 text-gray-700 
                    font-semibold rounded-lg shadow-md text-sm
                    hover:bg-green-300 focus:outline-none focus:ring-2 focus:ring-green-300
                    active:bg-green-600 transition-colors duration-150"
            >
                {props.user ? "Logga ut" : "Logga in"}
            </button>   


            <div 
                className="relative inline-block my-auto mr-3 order-4 hover:text-gray-700 text-gray-1000 active:scale-96"
                onClick={() => navigate("/cart")}
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-9">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                </svg>
                <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs w-4 h-4 flex items-center justify-center rounded-full">
                    {props.cartItems.length}
                </span>
            </div>

        </div>
    );

})
    