import { observer } from "mobx-react-lite";
import { logout } from "../firestoreModel"
import { useNavigate, useLocation } from "react-router-dom";
import { Utils } from "../utilities";

export const HeaderView = observer(function HeaderRender(props) {

    const navigate = useNavigate();
    const location = useLocation();
    const isCartPage = location.pathname === "/cart";

    return (
        <div 
            className="flex flex-wrap justify-between gap-5 w-full p-3 bg-green-100"
        >

            <div 
                className="items-center order-1
                    inline-block transform transition-transform 
                    duration-200 hover:scale-102 active:scale-98"
                onClick={() => navigate("/")}
            >
                {/* Icon base generated by chatgpt */}
                <svg width="120" height="66" viewBox="0 0 146 66" xmlns="http://www.w3.org/2000/svg">
                    {/* <circle cx="30" cy="30" r="20" fill="#34D399" />

                    <line x1="20" y1="25" x2="40" y2="25" stroke="white" strokeWidth="3" strokeLinecap="round"/>
                    <line x1="25" y1="20" x2="25" y2="40" stroke="white" strokeWidth="3" strokeLinecap="round"/> */}

                    <text x="10" y="30" fontFamily="Arial, sans-serif" fontSize="27" fill="#10B981" fontWeight="bold">
                        <tspan x="10" dy="0">Kampanj</tspan>
                        <tspan x="50" dy="26">Gruvan</tspan>
                    </text>
                </svg>
            </div>

            <div className="flex-grow order-last md:order-2 mx-auto my-auto min-w-[90%] md:min-w-[10%]">
                <div className="relative">
                    <span className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
                    🔍
                    </span>

                    <input
                        type="text"
                        placeholder="Sök efter dina favoritbutiker"
                        value={props.searchInput}
                        onFocus={() => props.setSearchFocus(true)}
                        onChange={(e) => props.setCurrentSearch(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 border border-gray-300 
                            rounded-full shadow-sm focus:outline-none focus:ring-2 
                            focus:ring-green-200 focus:border-green-400 transition"
                    />
                </div>
            </div>

            <button
                onClick={props.handleGetLocation}
                className="flex flex-col order-3 items-center px-2 py-1 rounded hover:bg-green-200 transition relative"
                title={"Hitta min plats"}
            >
                {/* Map pin icon generated by ChatGPT */}
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-9 h-9 text-green-700"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                >
                    <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5S10.62 6.5 12 6.5s2.5 1.12 2.5 2.5S13.38 11.5 12 11.5z" />
                </svg>

                <span className="text-xs text-green-900 mt-1 whitespace-nowrap">
                    {props.city || "Stockholm"}
                </span>
            </button>

            <button 
                onClick={props.user ? logout : ()=> navigate("/login")}
                className="ml-auto order-4 px-3 py-2 my-auto bg-green-400 text-gray-700 
                    font-semibold rounded-lg shadow-md text-sm
                    hover:bg-green-300 focus:outline-none focus:ring-2 focus:ring-green-300
                    active:bg-green-600 transition-colors duration-150"
            >
                {props.user ? "Logga ut" : "Logga in"}
            </button>   


            <div 
                className="relative inline-block my-auto mr-3 order-5 hover:text-gray-700 text-gray-1000 active:scale-96"
                onClick={() => {
                    if (isCartPage) {
                        navigate("/");
                    } else {
                        props.setSearchFocus(false);
                        navigate("/cart");
                    }
                }}
            >
                {isCartPage ? (
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-9">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                    </svg>
                ) : (
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-9">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                    </svg>
                )}
                {!isCartPage && (
                    <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs w-4 h-4 flex items-center justify-center rounded-full">
                        {props.cartItems.length}
                    </span>
                )}
            </div>

        </div>
    );

})